parameters:
    env(DATABASE_URL): 'pgsql://postgres:root@127.0.0.1:5432/db_name'

doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '11'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App\Modules:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
