security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        # Generate your own password by running bin/console security:encode-password. The default password is => admin
                        password: '$argon2i$v=19$m=1024,t=2,p=2$QW84d09jaEUxUDZDSnZQQw$31KuNnyB3Z4M3M/CaRXff94cvvemcInPcWvfK3CoxQ4'
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: 'argon2i'
            memory_cost: 1024
            time_cost: 2
            threads: 2

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            anonymous: ~
            http_basic: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
