version: "3"
services:
    symfony-skeleton:
        build: .
        container_name: "logs-viewer"
        working_dir: /var/www
        volumes:
            - ./:/var/www:delegated
        ports:
            - 85:80