parameters:
    localeEn: en-us
    localeCs: cs-cz
    locale: '%localeEn%'


    assets_dir: '%public_dir%/assets'
    assets_front_dir: '%assets_dir%/front'
    node_modules_dir: '%kernel.project_dir%/node_modules'
    public_dir: '%kernel.project_dir%/public'
    webtemp_dir: '%public_dir%/webtemp'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
